### ISSUE TITLE
Handling __attribute__ ((constructor)) functions

### ISSUE THREAD

**Issue by YoungseokCh** [3-24/print_function#1]
When I apply this to openssl, it crashes because it calls `print_func` before `init_out_file`.
```
Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=0x0, format=0x79aadd "%lu %s at %s\n",
    ap=ap@entry=0x7fffffffda80) at vfprintf.c:1283
1283    vfprintf.c: No such file or directory.
(gdb) bt
#0  _IO_vfprintf_internal (s=0x0, format=0x79aadd "%lu %s at %s\n",
    ap=ap@entry=0x7fffffffda80) at vfprintf.c:1283
#1  0x00007ffff6ce4e14 in __fprintf (stream=<optimized out>, format=<optimized out>)
    at fprintf.c:32
#2  0x000000000069dce2 in print_func (is_entry=true,
    file_name=0x765f5d "openssl/crypto/cryptlib.c",
    func_name=0x765f49 "OPENSSL_cpuid_setup") at src/print-function-rt.cpp:38
#3  0x000000000040df96 in OPENSSL_cpuid_setup () at crypto/cryptlib.c:98
#4  0x00000000004028af in _init () at crypto/x86_64cpuid.s:4
#5  0x0000000000011c30 in ?? ()
#6  0x00000000006ee241 in __libc_csu_init ()
#7  0x00007ffff6ca1c18 in __libc_start_main (main=0x404530 <main>, argc=2,
    argv=0x7fffffffddb8, init=0x6ee210 <__libc_csu_init>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffdda8) at ../csu/libc-start.c:266
#8  0x000000000040406a in _start ()
```

`OPENSSL_cpuid_setup` is defined with `__attribute__ ((constructor))`, so it is called before calling main. Following is the code snippet in `openssl/crypto/armcap.c`

```
# if defined(__GNUC__) && __GNUC__>=2
void OPENSSL_cpuid_setup(void) __attribute__ ((constructor));
# endif
```

**Comment by YoungseokCh** [comment]
Currently I don't know how to deal with such case. I will make the pass to ignore the static constructor functions that called before main.
